### ISSUE TITLE
problem with live videos

### ISSUE THREAD

**Issue by katastreet** [jessecordeiro/youtube-trending-videos-scraper#1]
your scraper has problem with live videos. Do check once.

**Comment by jecordei** [comment]
@katastreet Sorry for the late reply. What is the issue? I can't seem to reproduce the issue because there aren't any trending videos that are live at the moment.

**Comment by katastreet** [comment]
```
video_page_response = requests.get(Scraper.URL.format(country_code) + video_obj["video_url"])
				video_obj["upload_date"] = BeautifulSoup(video_page_response.text, "html.parser").select("strong.watch-time-text")[0].string
```

this line(line 60) throws an exception when a video that is trending is live and fetching is done at that time( i observed this during jimmy kimmel live show)

**Comment by jecordei** [comment]
@katastreet I still couldn't reproduce this issue despite having a live video that was trending. I've tried to handle the issue that you've reported with my latest commit. Pull from `master` and let me know if this fixes things for you. 🛠️

**Comment by katastreet** [comment]
@jessecordeiro  thanks man looks good now
